version: '3.8'
services:
  orders-svc:
    container_name: orders-svc
    build: ./apps/orders-svc/
    ports:
      - '3333:3333'
    volumes:
      - .:/workspace

  nginx:
    restart: always
    build:
      context: ./.nginx
    ports:
      - "80:80"
