version: '3.8'
services:
  checkout:
    container_name: checkout
    build:
      context: .
      dockerfile: ./apps/checkout/Dockerfile
      target: development
    command: yarn nx serve checkout
    ports:
      - 3333:3333
    depends_on:
      - rabbitmq
    volumes:
      - .:/workspace

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  nginx:
    restart: always
    build:
      context: ./.nginx
    ports:
      - 80:80
    depends_on:
      - rabbitmq
      - checkout
