version: '3.8'
services:
  checkout:
    container_name: checkout
    build:
      context: .
      dockerfile: ./apps/checkout/Dockerfile
      target: development
    command: yarn nx serve checkout
    ports:
      - 3333:3333
    depends_on:
      - rabbitmq
    volumes:
      - .:/workspace
      - /workspace/node_modules

  billing:
    container_name: billing
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: yarn nx serve billing
    depends_on:
      - rabbitmq
    volumes:
      - .:/workspace
      - /workspace/node_modules

  logistics:
    container_name: logistics
    build:
      context: .
      dockerfile: ./apps/logistics/Dockerfile
      target: development
    command: yarn nx serve logistics
    depends_on:
      - rabbitmq
    volumes:
      - .:/workspace
      - /workspace/node_modules

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  nginx:
    restart: always
    build:
      context: ./.nginx
    ports:
      - 80:80
    depends_on:
      - rabbitmq
      - checkout
