version: '3.8'
services:
  orders-svc:
    container_name: orders-svc
    build:
      context: .
      dockerfile: ./apps/orders-svc/Dockerfile
      target: development
    command: yarn nx serve orders-svc
    ports:
      - 3333:3333
    depends_on:
      - rabbitmq
    volumes:
      - .:/workspace

  nginx:
    restart: always
    build:
      context: ./.nginx
    ports:
      - 80:80
    depends_on:
      - rabbitmq
      - orders-svc
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - 5672:5672
      - 15672:15672
