version: '3.8'
services:
  orders-svc:
    container_name: orders-svc
    build:
      context: .
      dockerfile: ./apps/orders-svc/Dockerfile
      target: development
    command: yarn nx serve orders-svc
    ports:
      - '3333:3333'
    volumes:
      - .:/workspace

  nginx:
    restart: always
    build:
      context: ./.nginx
    ports:
      - "80:80"
