version: '3.8'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'

  nginx:
    restart: always
    build:
      context: ./.nginx
    ports:
      - 80:80
    depends_on:
      - rabbitmq
      - checkout
